<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ListadoSucursalesSeleccionados.aspx.cs" Inherits="TP7_Grupo7.ListadoSucursalesSeleccionados" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <link href="StyleSheet1.css" rel="stylesheet" />
</head>
<body class="body-listado">
    <form id="form1" runat="server">
        <div class="contenedor-wide">
            <div class="nav-bar">
                <asp:HyperLink ID="HyperLink1" runat="server" NavigateUrl="~/SeleccionarSucursales.aspx" CssClass="nav-link">Listado de sucursales</asp:HyperLink>
                <asp:HyperLink ID="HyperLink2" runat="server" NavigateUrl="~/ListadoSucursalesSeleccionados.aspx" CssClass="nav-link">Mostrar sucursales seleccionadas</asp:HyperLink>
            </div>

            <h2 class="titulo-seccion">MOSTRAR SUCURSALES SELECCIONADAS</h2>

            <div class="barra-busqueda">
                <asp:Label ID="lblBuscar" runat="server" Text="Buscar por nombre: " CssClass="lbl-campo"></asp:Label>
                <asp:TextBox ID="txtBuscar" runat="server" CssClass="input-campo" Width="250px"></asp:TextBox>
                <asp:Button ID="btnBuscar" runat="server" Text="Buscar" OnClick="btnBuscar_Click" CausesValidation="False" CssClass="btn-principal" />
            </div>

            <asp:Label ID="lblMensaje" runat="server" CssClass="lbl-mensaje"></asp:Label>

            <asp:GridView ID="gvSucursales" runat="server" 
                AllowSorting="true" 
                OnSorting="gvSucursales_Sorting" 
                AutoGenerateColumns="False" 
                CssClass="gridview-listado"
                CellPadding="3" 
                GridLines="Horizontal" 
                AutoGenerateDeleteButton="True" 
                OnRowDeleting="gvSucursales_RowDeleting">
                <AlternatingRowStyle CssClass="fila-alt" />
                <HeaderStyle CssClass="header-grid" />
                <RowStyle CssClass="fila-normal" />
                <Columns>
                    <asp:BoundField DataField="Id_Sucursal" HeaderText="ID Sucursal" SortExpression="Id_Sucursal" />
                    <asp:BoundField DataField="NombreSucursal" HeaderText="Nombre" SortExpression="NombreSucursal" />
                    <asp:BoundField DataField="DescripcionSucursal" HeaderText="Descripcion" SortExpression="DescripcionSucursal" />
                    <asp:BoundField DataField="DireccionSucursal" HeaderText="Ubicación" SortExpression="DireccionSucursal" />
                    <asp:BoundField DataField="DescripcionHorario" HeaderText="Horarios" SortExpression="DescripcionHorario" />
                </Columns>
            </asp:GridView>

            <div class="acciones">
                <asp:LinkButton ID="LB_Dese" runat="server" OnClick="LinkButton1_Click" CssClass="btn-eliminar">Deseleccionar todo</asp:LinkButton>
            </div>
        </div>
    </form>
</body>
</html>